/**
 * Handcrafted fixture mimicking Sleeper's `/v1/players/nfl` shape. Covers IDP,
 * inactive/retired, mixed/granular positions, full_name-only names, null ranks,
 * undraftable positions, team-less (unsigned) players, and — the case real data
 * forced — players Sleeper still calls active years after they stopped playing.
 * The builder is tested offline against this (CONVENTIONS §6). Not a test file.
 */
import type { SleeperPlayerMap } from './sleeper.js';

export const SLEEPER_FIXTURE: SleeperPlayerMap = {
  // QB — 3 provided, cap will keep 2. `qbCaleb` uses full_name only (name-split test).
  qbCaleb: {
    first_name: null,
    last_name: null,
    full_name: 'Caleb Williams',
    position: 'QB',
    team: 'CHI',
    search_rank: 1,
    active: true,
    depth_chart_order: 1,
  },
  qbMahomes: {
    player_id: 'qbMahomes',
    first_name: 'Patrick',
    last_name: 'Mahomes',
    position: 'QB',
    team: 'KC',
    search_rank: 5,
    active: true,
    depth_chart_order: 1,
  },
  qbAllen: {
    player_id: 'qbAllen',
    first_name: 'Josh',
    last_name: 'Allen',
    position: 'QB',
    team: 'BUF',
    search_rank: 10,
    active: true,
    depth_chart_order: 1,
  },

  // RB — 3 provided, cap keeps 2; Moss (worst rank) is dropped.
  rbBarkley: {
    player_id: 'rbBarkley',
    first_name: 'Saquon',
    last_name: 'Barkley',
    position: 'RB',
    team: 'PHI',
    search_rank: 3,
    active: true,
    depth_chart_order: 1,
  },
  rbBijan: {
    player_id: 'rbBijan',
    first_name: 'Bijan',
    last_name: 'Robinson',
    position: 'RB',
    team: 'ATL',
    search_rank: 8,
    active: true,
    depth_chart_order: 1,
  },
  rbMoss: {
    player_id: 'rbMoss',
    first_name: 'Zack',
    last_name: 'Moss',
    position: 'RB',
    team: 'CIN',
    search_rank: 200,
    active: true,
    depth_chart_order: 1,
  },

  // WR — includes a null-search_rank player that must sort last and be dropped.
  wrJefferson: {
    player_id: 'wrJefferson',
    first_name: 'Justin',
    last_name: 'Jefferson',
    position: 'WR',
    team: 'MIN',
    search_rank: 1,
    active: true,
    depth_chart_order: 1,
  },
  wrChase: {
    player_id: 'wrChase',
    first_name: "Ja'Marr",
    last_name: 'Chase',
    position: 'WR',
    team: 'CIN',
    search_rank: 2,
    active: true,
    depth_chart_order: 1,
  },
  wrNoRank: {
    player_id: 'wrNoRank',
    first_name: 'Unranked',
    last_name: 'Receiver',
    position: 'WR',
    team: 'HOU',
    search_rank: null,
    active: true,
    depth_chart_order: 1,
  },

  teKelce: {
    player_id: 'teKelce',
    first_name: 'Travis',
    last_name: 'Kelce',
    position: 'TE',
    team: 'KC',
    search_rank: 20,
    active: true,
    depth_chart_order: 1,
  },
  kButker: {
    player_id: 'kButker',
    first_name: 'Harrison',
    last_name: 'Butker',
    position: 'K',
    team: 'KC',
    search_rank: 300,
    active: true,
    depth_chart_order: 1,
  },
  defPHI: {
    player_id: 'PHI',
    first_name: 'Philadelphia',
    last_name: 'Eagles',
    position: 'DEF',
    team: 'PHI',
    search_rank: 400,
    active: true,
    // Deliberately no depth chart and no news — that is exactly how Sleeper
    // carries team defenses, and why `isCurrent` has to exempt them.
  },

  // IDP — granular positions collapse to DL/LB/DB and must survive the cap.
  dlGarrett: {
    player_id: 'dlGarrett',
    first_name: 'Myles',
    last_name: 'Garrett',
    position: 'DE',
    team: 'CLE',
    fantasy_positions: ['DL'],
    search_rank: 500,
    active: true,
    depth_chart_order: 1,
  },
  dlDonald: {
    player_id: 'dlDonald',
    first_name: 'Aaron',
    last_name: 'Donald',
    position: 'DT',
    team: 'LAR',
    search_rank: 510,
    active: true,
    depth_chart_order: 1,
  },
  lbWarner: {
    player_id: 'lbWarner',
    first_name: 'Fred',
    last_name: 'Warner',
    position: 'LB',
    team: 'SF',
    search_rank: 520,
    active: true,
    depth_chart_order: 1,
  },
  lbSmith: {
    player_id: 'lbSmith',
    first_name: 'Roquan',
    last_name: 'Smith',
    position: 'ILB',
    team: 'BAL',
    search_rank: 530,
    active: true,
    depth_chart_order: 1,
  },
  dbGardner: {
    player_id: 'dbGardner',
    first_name: 'Sauce',
    last_name: 'Gardner',
    position: 'CB',
    team: 'NYJ',
    search_rank: 540,
    active: true,
    depth_chart_order: 1,
  },
  // Position resolvable only via fantasy_positions.
  dbJames: {
    player_id: 'dbJames',
    first_name: 'Derwin',
    last_name: 'James',
    position: null,
    team: 'LAC',
    fantasy_positions: ['DB'],
    search_rank: 550,
    active: true,
    depth_chart_order: 1,
  },

  // Excluded: no current team (unsigned FA) even with a top rank — must be dropped.
  faTopWR: {
    player_id: 'faTopWR',
    first_name: 'Unsigned',
    last_name: 'Freeagent',
    position: 'WR',
    search_rank: 0,
    active: true,
    depth_chart_order: 1,
  },

  // Excluded: inactive, retired, and an undraftable position — all must vanish.
  // The Roethlisberger case, from real Sleeper data: every flag says starting QB,
  // but no depth chart and the last news item is four years old.
  qbRetiredButActive: {
    player_id: 'qbRetiredButActive',
    first_name: 'Ben',
    last_name: 'Roethlisberger',
    position: 'QB',
    team: 'PIT',
    search_rank: 2,
    active: true,
    status: 'Active',
    news_updated: 1_643_296_817_250,
  },
  // No depth chart, but news this week — a practice-squad or deep-bench player.
  // Must survive: ~300 genuinely current players look exactly like this.
  wrFreshNewsNoDepthChart: {
    player_id: 'wrFreshNewsNoDepthChart',
    first_name: 'Fresh',
    last_name: 'Newsman',
    position: 'WR',
    team: 'SEA',
    search_rank: 3,
    active: true,
    news_updated: 1_788_700_000_000,
  },
  inactiveWR: {
    player_id: 'inactiveWR',
    first_name: 'Retired',
    last_name: 'Star',
    position: 'WR',
    team: 'DAL',
    search_rank: 1,
    active: false,
    depth_chart_order: 1,
  },
  retiredRB: {
    player_id: 'retiredRB',
    first_name: 'Gone',
    last_name: 'Fishing',
    position: 'RB',
    team: 'GB',
    status: 'Retired',
    search_rank: 4,
    active: true,
    depth_chart_order: 1,
  },
  punter1: {
    player_id: 'punter1',
    first_name: 'Punt',
    last_name: 'Guy',
    position: 'P',
    team: 'DEN',
    search_rank: 250,
    active: true,
    depth_chart_order: 1,
  },
};
